sudo: false

language: php

php: 
    - 5.4
    - 5.5
    - 5.6
    - 7.0

install:
    - composer --prefer-source install

script:
    - phpunit .

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9f8cb52137601de70421
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
