sudo: false

language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: deps=high
        - php: 7
          env: deps=low

env:
    global:
        - deps=no

before_install:
    - if [ "$deps" != "skip" ]; then composer self-update; fi;

install:
    - if [ "$deps" = "no" ]; then composer --prefer-source install; fi;

script: phpunit -c app
