sudo: false

language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7

before_install:
    - export PHPUNIT="$(readlink -f ./phpunit)"

install:
    - composer --prefer-source install

script:
    - $PHPUNIT .