sudo: false

language: php

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mariadb
    - php: 5.5
      env: DB=mysql
    - php: 5.5
      env: DB=mariadb
    - php: 5.6
      env: DB=mysql
    - php: 5.6
      env: DB=mariadb
    - php: 7.0
      env: DB=mysql
    - php: 7.0
      env: DB=mariadb
  allow_failures:
    - php: 7.0
  fast_finish: true

before_script: 
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --prefer-source
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console self:fixtures:load -n --env=test

script:
    - phpunit -c app

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9f8cb52137601de70421
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

addons:
  mariadb: '10.0'
