imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    # http://blog.eleven-labs.com/symfony-2-cache-http-esi/
    fragments:       { path: /_proxy }
    esi:             true
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: v4.0.0
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:     session.handler.pdo
        #save_path: "%kernel.root_dir%/sessions"
        #name: "self"
    http_method_override: true

parameters:
    pdo.db_options:
        db_table:        session_pdo
        db_id_col:      session_id
        db_data_col: session_value
        db_time_col: session_time

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Innova\SelfBundle\Entity\User
    registration:
        form:
            type: innova_selfbundle_user
    from_email:
        address:        self@innovalangues.net
        sender_name:    SELF Innovalangues

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    external_plugins:
        selfemoticon:
            url: "asset[bundles/innovaself/plugins/selfemoticon/plugin.min.js]"
    theme:
        # Simple theme: same as default theme
        # Advanced theme with almost all enabled plugins
        simple:
            forced_root_block: false
            plugins:
                "charmap advlist autolink link image charmap hr searchreplace  visualchars paste selfemoticon "
            toolbar1: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | charmap selfemoticon "
            paste_auto_cleanup_on_paste : true
            paste_remove_styles: true
            paste_remove_styles_if_webkit: true
            paste_text_sticky: true
            paste_text_sticky_default: true
            paste_strip_class_attributes: true
            relative_urls : false

avalanche_imagine:
    source_root:  %kernel.root_dir%/../web/upload/media
    web_root:     %kernel.root_dir%/../web
    cache_prefix: upload/thumbnail
    driver:       gd
    filters:
        app4:
            type:    thumbnail
            options: { size: [120, 118], mode: outbound }
        app3:
            type:    thumbnail
            options: { size: [174, 118], mode: outbound }

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    []

fos_http_cache:
    cache_manager:
        enabled: %cache_manager_enabled%
    proxy_client:
        varnish:
            servers: %varnish_servers%
            base_url: %base_url%
    user_context:
        enabled: false
        role_provider: true
    flash_message:
        enabled: true
        name: flashes
    cache_control :
        rules:
            -
                match:
                    path: ^/login
                headers:

                    cache_control:
                        public: false
                        max_age: 0
                        s_maxage: 0
            -
                match:
                    path: ^/
                headers:
                    cache_control:
                        public: true
                        max_age: 3600
                        s_maxage: 3600

jms_i18n_routing:
    default_locale: fr
    locales: [fr, en, it]
    strategy: prefix_except_default