imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

parameters:
    router.request_context.base_url: %base_url_prod%

snc_redis:
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
        query_cache:
            client: cache
            entity_manager: default
