<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20151215152334 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE mediaClick (id INT AUTO_INCREMENT NOT NULL, media_id INT DEFAULT NULL, test_id INT DEFAULT NULL, questionnaire_id INT DEFAULT NULL, session_id INT DEFAULT NULL, component_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_E55542ECEA9FDD75 (media_id), INDEX IDX_E55542EC1E5D0459 (test_id), INDEX IDX_E55542ECCE07E8FF (questionnaire_id), INDEX IDX_E55542EC613FECDF (session_id), INDEX IDX_E55542ECE2ABAFFF (component_id), INDEX IDX_E55542ECA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media (id INT AUTO_INCREMENT NOT NULL, description LONGTEXT DEFAULT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, mediaType_id INT DEFAULT NULL, mediaPurpose_id INT DEFAULT NULL, INDEX IDX_6A2CA10C4FBBC852 (mediaType_id), INDEX IDX_6A2CA10C58630072 (mediaPurpose_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mediaPurpose (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mediaLimit (id INT AUTO_INCREMENT NOT NULL, media_id INT DEFAULT NULL, questionnaire_id INT DEFAULT NULL, listeningLimit INT NOT NULL, INDEX IDX_203568ACEA9FDD75 (media_id), INDEX IDX_203568ACCE07E8FF (questionnaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mediaType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE self_user (id INT AUTO_INCREMENT NOT NULL, institution_id INT DEFAULT NULL, course_id INT DEFAULT NULL, year_id INT DEFAULT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, locale VARCHAR(2) DEFAULT NULL, firstName VARCHAR(255) DEFAULT NULL, originStudent_id INT DEFAULT NULL, coLevel_id INT DEFAULT NULL, ceLevel_id INT DEFAULT NULL, eeLevel_id INT DEFAULT NULL, preferedLanguage_id INT DEFAULT NULL, levelLansad_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_3303DEF892FC23A8 (username_canonical), UNIQUE INDEX UNIQ_3303DEF8A0D96FBF (email_canonical), INDEX IDX_3303DEF874DBA9A1 (originStudent_id), INDEX IDX_3303DEF810405986 (institution_id), INDEX IDX_3303DEF8591CC992 (course_id), INDEX IDX_3303DEF840C1FEA7 (year_id), INDEX IDX_3303DEF899656FE8 (coLevel_id), INDEX IDX_3303DEF8C4BE576 (ceLevel_id), INDEX IDX_3303DEF81559531 (eeLevel_id), INDEX IDX_3303DEF8AE3BFE06 (preferedLanguage_id), INDEX IDX_3303DEF8BEAECE74 (levelLansad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_test (user_id INT NOT NULL, test_id INT NOT NULL, INDEX IDX_A2FE32C5A76ED395 (user_id), INDEX IDX_A2FE32C51E5D0459 (test_id), PRIMARY KEY(user_id, test_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_test_favorites (user_id INT NOT NULL, test_id INT NOT NULL, INDEX IDX_D712866A76ED395 (user_id), INDEX IDX_D7128661E5D0459 (test_id), PRIMARY KEY(user_id, test_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireGenre (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireTextLength (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireReception (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireSourceOperation (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SourceType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireStatus (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireFlow (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireCognitiveOperation (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireFocus (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireLength (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireSource (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireVariety (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireDomain (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireProductionType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireRegister (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Channel (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SocialLocation (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireAuthorRight (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireSkill (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill_typology (skill_id INT NOT NULL, typology_id INT NOT NULL, INDEX IDX_573EA50A5585C142 (skill_id), INDEX IDX_573EA50AC7D98C7A (typology_id), PRIMARY KEY(skill_id, typology_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireLevel (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clue (id INT AUTO_INCREMENT NOT NULL, media_id INT DEFAULT NULL, clueType_id INT DEFAULT NULL, INDEX IDX_268AADD1DCC8E71F (clueType_id), INDEX IDX_268AADD1EA9FDD75 (media_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE language (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaire (id INT AUTO_INCREMENT NOT NULL, level_id INT DEFAULT NULL, author_id INT DEFAULT NULL, status_id INT DEFAULT NULL, language_id INT DEFAULT NULL, skill_id INT DEFAULT NULL, source_id INT DEFAULT NULL, domain_id INT DEFAULT NULL, register_id INT DEFAULT NULL, reception_id INT DEFAULT NULL, length_id INT DEFAULT NULL, flow_id INT DEFAULT NULL, authorMore LONGTEXT DEFAULT NULL, theme VARCHAR(255) NOT NULL, textTitle VARCHAR(255) DEFAULT NULL, dialogue INT NOT NULL, fixedOrder TINYINT(1) NOT NULL, lisibility VARCHAR(255) DEFAULT NULL, levelProof LONGTEXT DEFAULT NULL, authorRightMore LONGTEXT DEFAULT NULL, sourceMore LONGTEXT DEFAULT NULL, questionnaires_speechType LONGTEXT DEFAULT NULL, languageLevel_id INT DEFAULT NULL, mediaInstruction_id INT DEFAULT NULL, mediaContext_id INT DEFAULT NULL, mediaText_id INT DEFAULT NULL, mediaBlankText_id INT DEFAULT NULL, mediaFunctionalInstruction_id INT DEFAULT NULL, mediaFeedback_id INT DEFAULT NULL, authorRight_id INT DEFAULT NULL, sourceOperation_id INT DEFAULT NULL, productionType_id INT DEFAULT NULL, textLength_id INT DEFAULT NULL, INDEX IDX_7A64DAF5FB14BA7 (level_id), INDEX IDX_7A64DAFF675F31B (author_id), INDEX IDX_7A64DAF76421FD8 (languageLevel_id), INDEX IDX_7A64DAF6BF700BD (status_id), INDEX IDX_7A64DAFE4F20921 (mediaInstruction_id), INDEX IDX_7A64DAF4CA1D08C (mediaContext_id), INDEX IDX_7A64DAFE37A7189 (mediaText_id), INDEX IDX_7A64DAF48CF71AD (mediaBlankText_id), INDEX IDX_7A64DAF2664265C (mediaFunctionalInstruction_id), INDEX IDX_7A64DAF3DBB19BC (mediaFeedback_id), INDEX IDX_7A64DAF82F1BAF4 (language_id), INDEX IDX_7A64DAF5585C142 (skill_id), INDEX IDX_7A64DAF9C93745D (authorRight_id), INDEX IDX_7A64DAF953C1C61 (source_id), INDEX IDX_7A64DAF3E5F0C25 (sourceOperation_id), INDEX IDX_7A64DAF115F0EE5 (domain_id), INDEX IDX_7A64DAF3C62C6D1 (productionType_id), INDEX IDX_7A64DAF4976CB7E (register_id), INDEX IDX_7A64DAF7C14DF52 (reception_id), INDEX IDX_7A64DAF61ED455A (length_id), INDEX IDX_7A64DAF7B9E0E8B (textLength_id), INDEX IDX_7A64DAF7EB60D1B (flow_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaires_revisors (questionnaire_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_1DB20B11CE07E8FF (questionnaire_id), INDEX IDX_1DB20B11A76ED395 (user_id), PRIMARY KEY(questionnaire_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaires_sourceType (questionnaire_id INT NOT NULL, sourcetype_id INT NOT NULL, INDEX IDX_C727588DCE07E8FF (questionnaire_id), INDEX IDX_C727588D8A804EF6 (sourcetype_id), PRIMARY KEY(questionnaire_id, sourcetype_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaires_channel (questionnaire_id INT NOT NULL, channel_id INT NOT NULL, INDEX IDX_2C4F1700CE07E8FF (questionnaire_id), INDEX IDX_2C4F170072F5A1AA (channel_id), PRIMARY KEY(questionnaire_id, channel_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaires_socialLocation (questionnaire_id INT NOT NULL, sociallocation_id INT NOT NULL, INDEX IDX_751FEFBDCE07E8FF (questionnaire_id), INDEX IDX_751FEFBDAB556334 (sociallocation_id), PRIMARY KEY(questionnaire_id, sociallocation_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaires_genre (questionnaire_id INT NOT NULL, genre_id INT NOT NULL, INDEX IDX_98D383B5CE07E8FF (questionnaire_id), INDEX IDX_98D383B54296D31F (genre_id), PRIMARY KEY(questionnaire_id, genre_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaires_variety (questionnaire_id INT NOT NULL, variety_id INT NOT NULL, INDEX IDX_B6600850CE07E8FF (questionnaire_id), INDEX IDX_B660085078C2BC47 (variety_id), PRIMARY KEY(questionnaire_id, variety_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rights (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, attribute VARCHAR(255) DEFAULT NULL, class VARCHAR(255) DEFAULT NULL, rightGroup_id INT DEFAULT NULL, INDEX IDX_160D10314B7E84A (rightGroup_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE right_user (right_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_5A6BF9454976835 (right_id), INDEX IDX_5A6BF94A76ED395 (user_id), PRIMARY KEY(right_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE right_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE right_user_someone (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, target_id INT DEFAULT NULL, canCreate TINYINT(1) NOT NULL, canEdit TINYINT(1) NOT NULL, canDelete TINYINT(1) NOT NULL, canDeleteTrace TINYINT(1) NOT NULL, canEditPassword TINYINT(1) NOT NULL, canEditRights TINYINT(1) NOT NULL, INDEX IDX_5F235AD5A76ED395 (user_id), INDEX IDX_5F235AD5158E0B66 (target_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE right_user_task (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, target_id INT DEFAULT NULL, canCreate TINYINT(1) NOT NULL, canEdit TINYINT(1) NOT NULL, canDelete TINYINT(1) NOT NULL, canList TINYINT(1) NOT NULL, INDEX IDX_CE4EA1B5A76ED395 (user_id), INDEX IDX_CE4EA1B5158E0B66 (target_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE right_user_session (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, target_id INT DEFAULT NULL, canCreate TINYINT(1) NOT NULL, canEdit TINYINT(1) NOT NULL, canDelete TINYINT(1) NOT NULL, canList TINYINT(1) NOT NULL, canExportIndividual TINYINT(1) NOT NULL, canExportCollective TINYINT(1) NOT NULL, INDEX IDX_DE5ECC68A76ED395 (user_id), INDEX IDX_DE5ECC68158E0B66 (target_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE right_user_test (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, target_id INT DEFAULT NULL, canCreate TINYINT(1) NOT NULL, canEdit TINYINT(1) NOT NULL, canDelete TINYINT(1) NOT NULL, canList TINYINT(1) NOT NULL, canDuplicate TINYINT(1) NOT NULL, canManageSession TINYINT(1) NOT NULL, canManageTask TINYINT(1) NOT NULL, canAddTask TINYINT(1) NOT NULL, canReorderTasks TINYINT(1) NOT NULL, canDeleteTask TINYINT(1) NOT NULL, canEditTask TINYINT(1) NOT NULL, INDEX IDX_444F049CA76ED395 (user_id), INDEX IDX_444F049C158E0B66 (target_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE proposition (id INT AUTO_INCREMENT NOT NULL, subquestion_id INT DEFAULT NULL, media_id INT DEFAULT NULL, rightAnswer TINYINT(1) NOT NULL, INDEX IDX_C7CDC35351A7950A (subquestion_id), INDEX IDX_C7CDC353EA9FDD75 (media_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE levelLansad (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_369C754282F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, difficulty TINYINT(1) NOT NULL, phased TINYINT(1) NOT NULL, archived TINYINT(1) NOT NULL, phasedParams_id INT DEFAULT NULL, testOrigin_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_D87F7E0C4051DAF9 (phasedParams_id), INDEX IDX_D87F7E0C82F1BAF4 (language_id), INDEX IDX_D87F7E0C6FF0BF59 (testOrigin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE trace (id INT AUTO_INCREMENT NOT NULL, questionnaire_id INT DEFAULT NULL, component_id INT DEFAULT NULL, session_id INT DEFAULT NULL, test_id INT DEFAULT NULL, user_id INT DEFAULT NULL, date DATETIME NOT NULL, totalTime INT NOT NULL, userAgent VARCHAR(255) NOT NULL, difficulty INT NOT NULL, INDEX IDX_315BD5A1CE07E8FF (questionnaire_id), INDEX IDX_315BD5A1E2ABAFFF (component_id), INDEX IDX_315BD5A1613FECDF (session_id), INDEX IDX_315BD5A11E5D0459 (test_id), INDEX IDX_315BD5A1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_result (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, session_id INT DEFAULT NULL, general_score VARCHAR(255) DEFAULT NULL, eec_score VARCHAR(255) DEFAULT NULL, ce_score VARCHAR(255) DEFAULT NULL, co_score VARCHAR(255) DEFAULT NULL, INDEX IDX_7638DA2EA76ED395 (user_id), INDEX IDX_7638DA2E613FECDF (session_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE originStudent (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subquestion (id INT AUTO_INCREMENT NOT NULL, typology_id INT DEFAULT NULL, level_id INT DEFAULT NULL, media_id INT DEFAULT NULL, question_id INT DEFAULT NULL, clue_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, difficultyIndex VARCHAR(255) DEFAULT NULL, discriminationIndex VARCHAR(255) DEFAULT NULL, displayAnswer TINYINT(1) NOT NULL, mediaAmorce_id INT DEFAULT NULL, mediaSyllable_id INT DEFAULT NULL, INDEX IDX_BD67F4C7C7D98C7A (typology_id), INDEX IDX_BD67F4C75FB14BA7 (level_id), INDEX IDX_BD67F4C7EA9FDD75 (media_id), INDEX IDX_BD67F4C735D15B1A (mediaAmorce_id), INDEX IDX_BD67F4C71E27F6BF (question_id), INDEX IDX_BD67F4C7FCCE328B (clue_id), INDEX IDX_BD67F4C7753D356C (mediaSyllable_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subquestion_focuses (subquestion_id INT NOT NULL, focus_id INT NOT NULL, INDEX IDX_E0566DAE51A7950A (subquestion_id), INDEX IDX_E0566DAE51804B42 (focus_id), PRIMARY KEY(subquestion_id, focus_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subquestion_cognitiveOpsMain (subquestion_id INT NOT NULL, cognitiveoperation_id INT NOT NULL, INDEX IDX_7CDF40FE51A7950A (subquestion_id), INDEX IDX_7CDF40FEC6BC7840 (cognitiveoperation_id), PRIMARY KEY(subquestion_id, cognitiveoperation_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subquestion_cognitiveOpsSecondary (subquestion_id INT NOT NULL, cognitiveoperation_id INT NOT NULL, INDEX IDX_CF8AC49A51A7950A (subquestion_id), INDEX IDX_CF8AC49AC6BC7840 (cognitiveoperation_id), PRIMARY KEY(subquestion_id, cognitiveoperation_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireComment (id INT AUTO_INCREMENT NOT NULL, questionnaire_id INT DEFAULT NULL, user_id INT DEFAULT NULL, description_id INT DEFAULT NULL, date DATETIME NOT NULL, editDate DATETIME DEFAULT NULL, INDEX IDX_3B5C834ACE07E8FF (questionnaire_id), INDEX IDX_3B5C834AA76ED395 (user_id), INDEX IDX_3B5C834AD9F966B (description_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE questionnaireLanguageLevel (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE session (id INT AUTO_INCREMENT NOT NULL, test_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, passwd VARCHAR(255) NOT NULL, actif TINYINT(1) NOT NULL, globalScoreWording VARCHAR(255) NOT NULL, globalScoreShow TINYINT(1) NOT NULL, INDEX IDX_D044D5D41E5D0459 (test_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE session_pdo (session_id VARCHAR(255) NOT NULL, session_value LONGBLOB NOT NULL, session_time INT NOT NULL, sess_lifetime INT NOT NULL, PRIMARY KEY(session_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clueType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orderQuestionnaireTest (id INT AUTO_INCREMENT NOT NULL, test_id INT DEFAULT NULL, questionnaire_id INT DEFAULT NULL, displayOrder INT NOT NULL, INDEX IDX_964A1B6C1E5D0459 (test_id), INDEX IDX_964A1B6CCE07E8FF (questionnaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE typology (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE question (id INT AUTO_INCREMENT NOT NULL, questionnaire_id INT DEFAULT NULL, typology_id INT DEFAULT NULL, INDEX IDX_B6F7494ECE07E8FF (questionnaire_id), INDEX IDX_B6F7494EC7D98C7A (typology_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE generalScoreThreshold (id INT AUTO_INCREMENT NOT NULL, level_id INT DEFAULT NULL, rightAnswers INT NOT NULL, description LONGTEXT DEFAULT NULL, componentType_id INT DEFAULT NULL, phasedParam_id INT DEFAULT NULL, INDEX IDX_3F79B3722FDB59F6 (componentType_id), INDEX IDX_3F79B3725FB14BA7 (level_id), INDEX IDX_3F79B3724741BDE4 (phasedParam_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orderQuestionnaireComponent (id INT AUTO_INCREMENT NOT NULL, component_id INT DEFAULT NULL, questionnaire_id INT DEFAULT NULL, displayOrder INT NOT NULL, INDEX IDX_906E94DBE2ABAFFF (component_id), INDEX IDX_906E94DBCE07E8FF (questionnaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE componentType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ignoredLevel (id INT AUTO_INCREMENT NOT NULL, skill_id INT DEFAULT NULL, componentType_id INT DEFAULT NULL, phasedParam_id INT DEFAULT NULL, INDEX IDX_C2A2C5125585C142 (skill_id), INDEX IDX_C2A2C5122FDB59F6 (componentType_id), INDEX IDX_C2A2C5124741BDE4 (phasedParam_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phasedParams_levels (ignoredlevel_id INT NOT NULL, level_id INT NOT NULL, INDEX IDX_E2E951F7EC03175 (ignoredlevel_id), INDEX IDX_E2E951F75FB14BA7 (level_id), PRIMARY KEY(ignoredlevel_id, level_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skillScoreThreshold (id INT AUTO_INCREMENT NOT NULL, skill_id INT DEFAULT NULL, level_id INT DEFAULT NULL, rightAnswers INT NOT NULL, description LONGTEXT DEFAULT NULL, componentType_id INT DEFAULT NULL, phasedParam_id INT DEFAULT NULL, INDEX IDX_3CE007675585C142 (skill_id), INDEX IDX_3CE007672FDB59F6 (componentType_id), INDEX IDX_3CE007675FB14BA7 (level_id), INDEX IDX_3CE007674741BDE4 (phasedParam_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phasedParams (id INT AUTO_INCREMENT NOT NULL, thresholdToStep2 INT NOT NULL, thresholdToStep2Leveled INT NOT NULL, thresholdToStep3 INT NOT NULL, thresholdToStep3Leveled INT NOT NULL, thresholdToStep2Level_id INT DEFAULT NULL, thresholdToStep3Level_id INT DEFAULT NULL, INDEX IDX_9CD1CCF77B5D72 (thresholdToStep2Level_id), INDEX IDX_9CD1CCF717004931 (thresholdToStep3Level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE component (id INT AUTO_INCREMENT NOT NULL, test_id INT DEFAULT NULL, alternativeNumber INT NOT NULL, componentType_id INT DEFAULT NULL, INDEX IDX_49FEA1572FDB59F6 (componentType_id), INDEX IDX_49FEA1571E5D0459 (test_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE general_parameters (id INT AUTO_INCREMENT NOT NULL, maintenance TINYINT(1) NOT NULL, self_registration TINYINT(1) NOT NULL, maintenance_text LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE institution (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE year (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course (id INT AUTO_INCREMENT NOT NULL, institution_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_169E6FB910405986 (institution_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE answer (id INT AUTO_INCREMENT NOT NULL, trace_id INT DEFAULT NULL, proposition_id INT DEFAULT NULL, subquestion_id INT DEFAULT NULL, INDEX IDX_DADD4A25BE0D4B70 (trace_id), INDEX IDX_DADD4A25DB96F9E (proposition_id), INDEX IDX_DADD4A2551A7950A (subquestion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE mediaClick ADD CONSTRAINT FK_E55542ECEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE mediaClick ADD CONSTRAINT FK_E55542EC1E5D0459 FOREIGN KEY (test_id) REFERENCES test (id)');
        $this->addSql('ALTER TABLE mediaClick ADD CONSTRAINT FK_E55542ECCE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id)');
        $this->addSql('ALTER TABLE mediaClick ADD CONSTRAINT FK_E55542EC613FECDF FOREIGN KEY (session_id) REFERENCES session (id)');
        $this->addSql('ALTER TABLE mediaClick ADD CONSTRAINT FK_E55542ECE2ABAFFF FOREIGN KEY (component_id) REFERENCES component (id)');
        $this->addSql('ALTER TABLE mediaClick ADD CONSTRAINT FK_E55542ECA76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C4FBBC852 FOREIGN KEY (mediaType_id) REFERENCES mediaType (id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C58630072 FOREIGN KEY (mediaPurpose_id) REFERENCES mediaPurpose (id)');
        $this->addSql('ALTER TABLE mediaLimit ADD CONSTRAINT FK_203568ACEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE mediaLimit ADD CONSTRAINT FK_203568ACCE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id)');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF874DBA9A1 FOREIGN KEY (originStudent_id) REFERENCES originStudent (id)');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF810405986 FOREIGN KEY (institution_id) REFERENCES institution (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF8591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF840C1FEA7 FOREIGN KEY (year_id) REFERENCES year (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF899656FE8 FOREIGN KEY (coLevel_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF8C4BE576 FOREIGN KEY (ceLevel_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF81559531 FOREIGN KEY (eeLevel_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF8AE3BFE06 FOREIGN KEY (preferedLanguage_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE self_user ADD CONSTRAINT FK_3303DEF8BEAECE74 FOREIGN KEY (levelLansad_id) REFERENCES levelLansad (id)');
        $this->addSql('ALTER TABLE user_test ADD CONSTRAINT FK_A2FE32C5A76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_test ADD CONSTRAINT FK_A2FE32C51E5D0459 FOREIGN KEY (test_id) REFERENCES test (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_test_favorites ADD CONSTRAINT FK_D712866A76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_test_favorites ADD CONSTRAINT FK_D7128661E5D0459 FOREIGN KEY (test_id) REFERENCES test (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_typology ADD CONSTRAINT FK_573EA50A5585C142 FOREIGN KEY (skill_id) REFERENCES questionnaireSkill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_typology ADD CONSTRAINT FK_573EA50AC7D98C7A FOREIGN KEY (typology_id) REFERENCES typology (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE clue ADD CONSTRAINT FK_268AADD1DCC8E71F FOREIGN KEY (clueType_id) REFERENCES clueType (id)');
        $this->addSql('ALTER TABLE clue ADD CONSTRAINT FK_268AADD1EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF5FB14BA7 FOREIGN KEY (level_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAFF675F31B FOREIGN KEY (author_id) REFERENCES self_user (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF76421FD8 FOREIGN KEY (languageLevel_id) REFERENCES questionnaireLanguageLevel (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF6BF700BD FOREIGN KEY (status_id) REFERENCES questionnaireStatus (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAFE4F20921 FOREIGN KEY (mediaInstruction_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF4CA1D08C FOREIGN KEY (mediaContext_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAFE37A7189 FOREIGN KEY (mediaText_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF48CF71AD FOREIGN KEY (mediaBlankText_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF2664265C FOREIGN KEY (mediaFunctionalInstruction_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF3DBB19BC FOREIGN KEY (mediaFeedback_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF5585C142 FOREIGN KEY (skill_id) REFERENCES questionnaireSkill (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF9C93745D FOREIGN KEY (authorRight_id) REFERENCES questionnaireAuthorRight (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF953C1C61 FOREIGN KEY (source_id) REFERENCES questionnaireSource (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF3E5F0C25 FOREIGN KEY (sourceOperation_id) REFERENCES questionnaireSourceOperation (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF115F0EE5 FOREIGN KEY (domain_id) REFERENCES questionnaireDomain (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF3C62C6D1 FOREIGN KEY (productionType_id) REFERENCES questionnaireProductionType (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF4976CB7E FOREIGN KEY (register_id) REFERENCES questionnaireRegister (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF7C14DF52 FOREIGN KEY (reception_id) REFERENCES questionnaireReception (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF61ED455A FOREIGN KEY (length_id) REFERENCES questionnaireLength (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF7B9E0E8B FOREIGN KEY (textLength_id) REFERENCES questionnaireTextLength (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF7EB60D1B FOREIGN KEY (flow_id) REFERENCES questionnaireFlow (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE questionnaires_revisors ADD CONSTRAINT FK_1DB20B11CE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_revisors ADD CONSTRAINT FK_1DB20B11A76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_sourceType ADD CONSTRAINT FK_C727588DCE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_sourceType ADD CONSTRAINT FK_C727588D8A804EF6 FOREIGN KEY (sourcetype_id) REFERENCES SourceType (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_channel ADD CONSTRAINT FK_2C4F1700CE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_channel ADD CONSTRAINT FK_2C4F170072F5A1AA FOREIGN KEY (channel_id) REFERENCES Channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_socialLocation ADD CONSTRAINT FK_751FEFBDCE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_socialLocation ADD CONSTRAINT FK_751FEFBDAB556334 FOREIGN KEY (sociallocation_id) REFERENCES SocialLocation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_genre ADD CONSTRAINT FK_98D383B5CE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_genre ADD CONSTRAINT FK_98D383B54296D31F FOREIGN KEY (genre_id) REFERENCES questionnaireGenre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_variety ADD CONSTRAINT FK_B6600850CE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaires_variety ADD CONSTRAINT FK_B660085078C2BC47 FOREIGN KEY (variety_id) REFERENCES questionnaireVariety (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rights ADD CONSTRAINT FK_160D10314B7E84A FOREIGN KEY (rightGroup_id) REFERENCES right_group (id)');
        $this->addSql('ALTER TABLE right_user ADD CONSTRAINT FK_5A6BF9454976835 FOREIGN KEY (right_id) REFERENCES rights (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user ADD CONSTRAINT FK_5A6BF94A76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user_someone ADD CONSTRAINT FK_5F235AD5A76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user_someone ADD CONSTRAINT FK_5F235AD5158E0B66 FOREIGN KEY (target_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user_task ADD CONSTRAINT FK_CE4EA1B5A76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user_task ADD CONSTRAINT FK_CE4EA1B5158E0B66 FOREIGN KEY (target_id) REFERENCES questionnaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user_session ADD CONSTRAINT FK_DE5ECC68A76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user_session ADD CONSTRAINT FK_DE5ECC68158E0B66 FOREIGN KEY (target_id) REFERENCES session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user_test ADD CONSTRAINT FK_444F049CA76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE right_user_test ADD CONSTRAINT FK_444F049C158E0B66 FOREIGN KEY (target_id) REFERENCES test (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE proposition ADD CONSTRAINT FK_C7CDC35351A7950A FOREIGN KEY (subquestion_id) REFERENCES subquestion (id)');
        $this->addSql('ALTER TABLE proposition ADD CONSTRAINT FK_C7CDC353EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE levelLansad ADD CONSTRAINT FK_369C754282F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE test ADD CONSTRAINT FK_D87F7E0C4051DAF9 FOREIGN KEY (phasedParams_id) REFERENCES phasedParams (id)');
        $this->addSql('ALTER TABLE test ADD CONSTRAINT FK_D87F7E0C82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE test ADD CONSTRAINT FK_D87F7E0C6FF0BF59 FOREIGN KEY (testOrigin_id) REFERENCES test (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1CE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id)');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1E2ABAFFF FOREIGN KEY (component_id) REFERENCES component (id)');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1613FECDF FOREIGN KEY (session_id) REFERENCES session (id)');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A11E5D0459 FOREIGN KEY (test_id) REFERENCES test (id)');
        $this->addSql('ALTER TABLE trace ADD CONSTRAINT FK_315BD5A1A76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id)');
        $this->addSql('ALTER TABLE user_result ADD CONSTRAINT FK_7638DA2EA76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id)');
        $this->addSql('ALTER TABLE user_result ADD CONSTRAINT FK_7638DA2E613FECDF FOREIGN KEY (session_id) REFERENCES session (id)');
        $this->addSql('ALTER TABLE subquestion ADD CONSTRAINT FK_BD67F4C7C7D98C7A FOREIGN KEY (typology_id) REFERENCES typology (id)');
        $this->addSql('ALTER TABLE subquestion ADD CONSTRAINT FK_BD67F4C75FB14BA7 FOREIGN KEY (level_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE subquestion ADD CONSTRAINT FK_BD67F4C7EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE subquestion ADD CONSTRAINT FK_BD67F4C735D15B1A FOREIGN KEY (mediaAmorce_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE subquestion ADD CONSTRAINT FK_BD67F4C71E27F6BF FOREIGN KEY (question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE subquestion ADD CONSTRAINT FK_BD67F4C7FCCE328B FOREIGN KEY (clue_id) REFERENCES clue (id)');
        $this->addSql('ALTER TABLE subquestion ADD CONSTRAINT FK_BD67F4C7753D356C FOREIGN KEY (mediaSyllable_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE subquestion_focuses ADD CONSTRAINT FK_E0566DAE51A7950A FOREIGN KEY (subquestion_id) REFERENCES subquestion (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subquestion_focuses ADD CONSTRAINT FK_E0566DAE51804B42 FOREIGN KEY (focus_id) REFERENCES questionnaireFocus (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subquestion_cognitiveOpsMain ADD CONSTRAINT FK_7CDF40FE51A7950A FOREIGN KEY (subquestion_id) REFERENCES subquestion (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subquestion_cognitiveOpsMain ADD CONSTRAINT FK_7CDF40FEC6BC7840 FOREIGN KEY (cognitiveoperation_id) REFERENCES questionnaireCognitiveOperation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subquestion_cognitiveOpsSecondary ADD CONSTRAINT FK_CF8AC49A51A7950A FOREIGN KEY (subquestion_id) REFERENCES subquestion (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subquestion_cognitiveOpsSecondary ADD CONSTRAINT FK_CF8AC49AC6BC7840 FOREIGN KEY (cognitiveoperation_id) REFERENCES questionnaireCognitiveOperation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE questionnaireComment ADD CONSTRAINT FK_3B5C834ACE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id)');
        $this->addSql('ALTER TABLE questionnaireComment ADD CONSTRAINT FK_3B5C834AA76ED395 FOREIGN KEY (user_id) REFERENCES self_user (id)');
        $this->addSql('ALTER TABLE questionnaireComment ADD CONSTRAINT FK_3B5C834AD9F966B FOREIGN KEY (description_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D41E5D0459 FOREIGN KEY (test_id) REFERENCES test (id)');
        $this->addSql('ALTER TABLE orderQuestionnaireTest ADD CONSTRAINT FK_964A1B6C1E5D0459 FOREIGN KEY (test_id) REFERENCES test (id)');
        $this->addSql('ALTER TABLE orderQuestionnaireTest ADD CONSTRAINT FK_964A1B6CCE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494ECE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494EC7D98C7A FOREIGN KEY (typology_id) REFERENCES typology (id)');
        $this->addSql('ALTER TABLE generalScoreThreshold ADD CONSTRAINT FK_3F79B3722FDB59F6 FOREIGN KEY (componentType_id) REFERENCES componentType (id)');
        $this->addSql('ALTER TABLE generalScoreThreshold ADD CONSTRAINT FK_3F79B3725FB14BA7 FOREIGN KEY (level_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE generalScoreThreshold ADD CONSTRAINT FK_3F79B3724741BDE4 FOREIGN KEY (phasedParam_id) REFERENCES phasedParams (id)');
        $this->addSql('ALTER TABLE orderQuestionnaireComponent ADD CONSTRAINT FK_906E94DBE2ABAFFF FOREIGN KEY (component_id) REFERENCES component (id)');
        $this->addSql('ALTER TABLE orderQuestionnaireComponent ADD CONSTRAINT FK_906E94DBCE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id)');
        $this->addSql('ALTER TABLE ignoredLevel ADD CONSTRAINT FK_C2A2C5125585C142 FOREIGN KEY (skill_id) REFERENCES questionnaireSkill (id)');
        $this->addSql('ALTER TABLE ignoredLevel ADD CONSTRAINT FK_C2A2C5122FDB59F6 FOREIGN KEY (componentType_id) REFERENCES componentType (id)');
        $this->addSql('ALTER TABLE ignoredLevel ADD CONSTRAINT FK_C2A2C5124741BDE4 FOREIGN KEY (phasedParam_id) REFERENCES phasedParams (id)');
        $this->addSql('ALTER TABLE phasedParams_levels ADD CONSTRAINT FK_E2E951F7EC03175 FOREIGN KEY (ignoredlevel_id) REFERENCES ignoredLevel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE phasedParams_levels ADD CONSTRAINT FK_E2E951F75FB14BA7 FOREIGN KEY (level_id) REFERENCES questionnaireLevel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skillScoreThreshold ADD CONSTRAINT FK_3CE007675585C142 FOREIGN KEY (skill_id) REFERENCES questionnaireSkill (id)');
        $this->addSql('ALTER TABLE skillScoreThreshold ADD CONSTRAINT FK_3CE007672FDB59F6 FOREIGN KEY (componentType_id) REFERENCES componentType (id)');
        $this->addSql('ALTER TABLE skillScoreThreshold ADD CONSTRAINT FK_3CE007675FB14BA7 FOREIGN KEY (level_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE skillScoreThreshold ADD CONSTRAINT FK_3CE007674741BDE4 FOREIGN KEY (phasedParam_id) REFERENCES phasedParams (id)');
        $this->addSql('ALTER TABLE phasedParams ADD CONSTRAINT FK_9CD1CCF77B5D72 FOREIGN KEY (thresholdToStep2Level_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE phasedParams ADD CONSTRAINT FK_9CD1CCF717004931 FOREIGN KEY (thresholdToStep3Level_id) REFERENCES questionnaireLevel (id)');
        $this->addSql('ALTER TABLE component ADD CONSTRAINT FK_49FEA1572FDB59F6 FOREIGN KEY (componentType_id) REFERENCES componentType (id)');
        $this->addSql('ALTER TABLE component ADD CONSTRAINT FK_49FEA1571E5D0459 FOREIGN KEY (test_id) REFERENCES test (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB910405986 FOREIGN KEY (institution_id) REFERENCES institution (id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25BE0D4B70 FOREIGN KEY (trace_id) REFERENCES trace (id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25DB96F9E FOREIGN KEY (proposition_id) REFERENCES proposition (id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A2551A7950A FOREIGN KEY (subquestion_id) REFERENCES subquestion (id)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE mediaClick DROP FOREIGN KEY FK_E55542ECEA9FDD75');
        $this->addSql('ALTER TABLE mediaLimit DROP FOREIGN KEY FK_203568ACEA9FDD75');
        $this->addSql('ALTER TABLE clue DROP FOREIGN KEY FK_268AADD1EA9FDD75');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAFE4F20921');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF4CA1D08C');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAFE37A7189');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF48CF71AD');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF2664265C');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF3DBB19BC');
        $this->addSql('ALTER TABLE proposition DROP FOREIGN KEY FK_C7CDC353EA9FDD75');
        $this->addSql('ALTER TABLE subquestion DROP FOREIGN KEY FK_BD67F4C7EA9FDD75');
        $this->addSql('ALTER TABLE subquestion DROP FOREIGN KEY FK_BD67F4C735D15B1A');
        $this->addSql('ALTER TABLE subquestion DROP FOREIGN KEY FK_BD67F4C7753D356C');
        $this->addSql('ALTER TABLE questionnaireComment DROP FOREIGN KEY FK_3B5C834AD9F966B');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10C58630072');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10C4FBBC852');
        $this->addSql('ALTER TABLE mediaClick DROP FOREIGN KEY FK_E55542ECA76ED395');
        $this->addSql('ALTER TABLE user_test DROP FOREIGN KEY FK_A2FE32C5A76ED395');
        $this->addSql('ALTER TABLE user_test_favorites DROP FOREIGN KEY FK_D712866A76ED395');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAFF675F31B');
        $this->addSql('ALTER TABLE questionnaires_revisors DROP FOREIGN KEY FK_1DB20B11A76ED395');
        $this->addSql('ALTER TABLE right_user DROP FOREIGN KEY FK_5A6BF94A76ED395');
        $this->addSql('ALTER TABLE right_user_someone DROP FOREIGN KEY FK_5F235AD5A76ED395');
        $this->addSql('ALTER TABLE right_user_someone DROP FOREIGN KEY FK_5F235AD5158E0B66');
        $this->addSql('ALTER TABLE right_user_task DROP FOREIGN KEY FK_CE4EA1B5A76ED395');
        $this->addSql('ALTER TABLE right_user_session DROP FOREIGN KEY FK_DE5ECC68A76ED395');
        $this->addSql('ALTER TABLE right_user_test DROP FOREIGN KEY FK_444F049CA76ED395');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1A76ED395');
        $this->addSql('ALTER TABLE user_result DROP FOREIGN KEY FK_7638DA2EA76ED395');
        $this->addSql('ALTER TABLE questionnaireComment DROP FOREIGN KEY FK_3B5C834AA76ED395');
        $this->addSql('ALTER TABLE questionnaires_genre DROP FOREIGN KEY FK_98D383B54296D31F');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF7B9E0E8B');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF7C14DF52');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF3E5F0C25');
        $this->addSql('ALTER TABLE questionnaires_sourceType DROP FOREIGN KEY FK_C727588D8A804EF6');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF6BF700BD');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF7EB60D1B');
        $this->addSql('ALTER TABLE subquestion_cognitiveOpsMain DROP FOREIGN KEY FK_7CDF40FEC6BC7840');
        $this->addSql('ALTER TABLE subquestion_cognitiveOpsSecondary DROP FOREIGN KEY FK_CF8AC49AC6BC7840');
        $this->addSql('ALTER TABLE subquestion_focuses DROP FOREIGN KEY FK_E0566DAE51804B42');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF61ED455A');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF953C1C61');
        $this->addSql('ALTER TABLE questionnaires_variety DROP FOREIGN KEY FK_B660085078C2BC47');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF115F0EE5');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF3C62C6D1');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF4976CB7E');
        $this->addSql('ALTER TABLE questionnaires_channel DROP FOREIGN KEY FK_2C4F170072F5A1AA');
        $this->addSql('ALTER TABLE questionnaires_socialLocation DROP FOREIGN KEY FK_751FEFBDAB556334');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF9C93745D');
        $this->addSql('ALTER TABLE skill_typology DROP FOREIGN KEY FK_573EA50A5585C142');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF5585C142');
        $this->addSql('ALTER TABLE ignoredLevel DROP FOREIGN KEY FK_C2A2C5125585C142');
        $this->addSql('ALTER TABLE skillScoreThreshold DROP FOREIGN KEY FK_3CE007675585C142');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF899656FE8');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF8C4BE576');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF81559531');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF5FB14BA7');
        $this->addSql('ALTER TABLE subquestion DROP FOREIGN KEY FK_BD67F4C75FB14BA7');
        $this->addSql('ALTER TABLE generalScoreThreshold DROP FOREIGN KEY FK_3F79B3725FB14BA7');
        $this->addSql('ALTER TABLE phasedParams_levels DROP FOREIGN KEY FK_E2E951F75FB14BA7');
        $this->addSql('ALTER TABLE skillScoreThreshold DROP FOREIGN KEY FK_3CE007675FB14BA7');
        $this->addSql('ALTER TABLE phasedParams DROP FOREIGN KEY FK_9CD1CCF77B5D72');
        $this->addSql('ALTER TABLE phasedParams DROP FOREIGN KEY FK_9CD1CCF717004931');
        $this->addSql('ALTER TABLE subquestion DROP FOREIGN KEY FK_BD67F4C7FCCE328B');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF8AE3BFE06');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF82F1BAF4');
        $this->addSql('ALTER TABLE levelLansad DROP FOREIGN KEY FK_369C754282F1BAF4');
        $this->addSql('ALTER TABLE test DROP FOREIGN KEY FK_D87F7E0C82F1BAF4');
        $this->addSql('ALTER TABLE mediaClick DROP FOREIGN KEY FK_E55542ECCE07E8FF');
        $this->addSql('ALTER TABLE mediaLimit DROP FOREIGN KEY FK_203568ACCE07E8FF');
        $this->addSql('ALTER TABLE questionnaires_revisors DROP FOREIGN KEY FK_1DB20B11CE07E8FF');
        $this->addSql('ALTER TABLE questionnaires_sourceType DROP FOREIGN KEY FK_C727588DCE07E8FF');
        $this->addSql('ALTER TABLE questionnaires_channel DROP FOREIGN KEY FK_2C4F1700CE07E8FF');
        $this->addSql('ALTER TABLE questionnaires_socialLocation DROP FOREIGN KEY FK_751FEFBDCE07E8FF');
        $this->addSql('ALTER TABLE questionnaires_genre DROP FOREIGN KEY FK_98D383B5CE07E8FF');
        $this->addSql('ALTER TABLE questionnaires_variety DROP FOREIGN KEY FK_B6600850CE07E8FF');
        $this->addSql('ALTER TABLE right_user_task DROP FOREIGN KEY FK_CE4EA1B5158E0B66');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1CE07E8FF');
        $this->addSql('ALTER TABLE questionnaireComment DROP FOREIGN KEY FK_3B5C834ACE07E8FF');
        $this->addSql('ALTER TABLE orderQuestionnaireTest DROP FOREIGN KEY FK_964A1B6CCE07E8FF');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_B6F7494ECE07E8FF');
        $this->addSql('ALTER TABLE orderQuestionnaireComponent DROP FOREIGN KEY FK_906E94DBCE07E8FF');
        $this->addSql('ALTER TABLE right_user DROP FOREIGN KEY FK_5A6BF9454976835');
        $this->addSql('ALTER TABLE rights DROP FOREIGN KEY FK_160D10314B7E84A');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A25DB96F9E');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF8BEAECE74');
        $this->addSql('ALTER TABLE mediaClick DROP FOREIGN KEY FK_E55542EC1E5D0459');
        $this->addSql('ALTER TABLE user_test DROP FOREIGN KEY FK_A2FE32C51E5D0459');
        $this->addSql('ALTER TABLE user_test_favorites DROP FOREIGN KEY FK_D7128661E5D0459');
        $this->addSql('ALTER TABLE right_user_test DROP FOREIGN KEY FK_444F049C158E0B66');
        $this->addSql('ALTER TABLE test DROP FOREIGN KEY FK_D87F7E0C6FF0BF59');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A11E5D0459');
        $this->addSql('ALTER TABLE session DROP FOREIGN KEY FK_D044D5D41E5D0459');
        $this->addSql('ALTER TABLE orderQuestionnaireTest DROP FOREIGN KEY FK_964A1B6C1E5D0459');
        $this->addSql('ALTER TABLE component DROP FOREIGN KEY FK_49FEA1571E5D0459');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A25BE0D4B70');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF874DBA9A1');
        $this->addSql('ALTER TABLE proposition DROP FOREIGN KEY FK_C7CDC35351A7950A');
        $this->addSql('ALTER TABLE subquestion_focuses DROP FOREIGN KEY FK_E0566DAE51A7950A');
        $this->addSql('ALTER TABLE subquestion_cognitiveOpsMain DROP FOREIGN KEY FK_7CDF40FE51A7950A');
        $this->addSql('ALTER TABLE subquestion_cognitiveOpsSecondary DROP FOREIGN KEY FK_CF8AC49A51A7950A');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A2551A7950A');
        $this->addSql('ALTER TABLE questionnaire DROP FOREIGN KEY FK_7A64DAF76421FD8');
        $this->addSql('ALTER TABLE mediaClick DROP FOREIGN KEY FK_E55542EC613FECDF');
        $this->addSql('ALTER TABLE right_user_session DROP FOREIGN KEY FK_DE5ECC68158E0B66');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1613FECDF');
        $this->addSql('ALTER TABLE user_result DROP FOREIGN KEY FK_7638DA2E613FECDF');
        $this->addSql('ALTER TABLE clue DROP FOREIGN KEY FK_268AADD1DCC8E71F');
        $this->addSql('ALTER TABLE skill_typology DROP FOREIGN KEY FK_573EA50AC7D98C7A');
        $this->addSql('ALTER TABLE subquestion DROP FOREIGN KEY FK_BD67F4C7C7D98C7A');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_B6F7494EC7D98C7A');
        $this->addSql('ALTER TABLE subquestion DROP FOREIGN KEY FK_BD67F4C71E27F6BF');
        $this->addSql('ALTER TABLE generalScoreThreshold DROP FOREIGN KEY FK_3F79B3722FDB59F6');
        $this->addSql('ALTER TABLE ignoredLevel DROP FOREIGN KEY FK_C2A2C5122FDB59F6');
        $this->addSql('ALTER TABLE skillScoreThreshold DROP FOREIGN KEY FK_3CE007672FDB59F6');
        $this->addSql('ALTER TABLE component DROP FOREIGN KEY FK_49FEA1572FDB59F6');
        $this->addSql('ALTER TABLE phasedParams_levels DROP FOREIGN KEY FK_E2E951F7EC03175');
        $this->addSql('ALTER TABLE test DROP FOREIGN KEY FK_D87F7E0C4051DAF9');
        $this->addSql('ALTER TABLE generalScoreThreshold DROP FOREIGN KEY FK_3F79B3724741BDE4');
        $this->addSql('ALTER TABLE ignoredLevel DROP FOREIGN KEY FK_C2A2C5124741BDE4');
        $this->addSql('ALTER TABLE skillScoreThreshold DROP FOREIGN KEY FK_3CE007674741BDE4');
        $this->addSql('ALTER TABLE mediaClick DROP FOREIGN KEY FK_E55542ECE2ABAFFF');
        $this->addSql('ALTER TABLE trace DROP FOREIGN KEY FK_315BD5A1E2ABAFFF');
        $this->addSql('ALTER TABLE orderQuestionnaireComponent DROP FOREIGN KEY FK_906E94DBE2ABAFFF');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF810405986');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB910405986');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF840C1FEA7');
        $this->addSql('ALTER TABLE self_user DROP FOREIGN KEY FK_3303DEF8591CC992');
        $this->addSql('DROP TABLE mediaClick');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE mediaPurpose');
        $this->addSql('DROP TABLE mediaLimit');
        $this->addSql('DROP TABLE mediaType');
        $this->addSql('DROP TABLE self_user');
        $this->addSql('DROP TABLE user_test');
        $this->addSql('DROP TABLE user_test_favorites');
        $this->addSql('DROP TABLE questionnaireGenre');
        $this->addSql('DROP TABLE questionnaireTextLength');
        $this->addSql('DROP TABLE questionnaireReception');
        $this->addSql('DROP TABLE questionnaireSourceOperation');
        $this->addSql('DROP TABLE SourceType');
        $this->addSql('DROP TABLE questionnaireStatus');
        $this->addSql('DROP TABLE questionnaireFlow');
        $this->addSql('DROP TABLE questionnaireCognitiveOperation');
        $this->addSql('DROP TABLE questionnaireFocus');
        $this->addSql('DROP TABLE questionnaireLength');
        $this->addSql('DROP TABLE questionnaireSource');
        $this->addSql('DROP TABLE questionnaireVariety');
        $this->addSql('DROP TABLE questionnaireDomain');
        $this->addSql('DROP TABLE questionnaireProductionType');
        $this->addSql('DROP TABLE questionnaireRegister');
        $this->addSql('DROP TABLE Channel');
        $this->addSql('DROP TABLE SocialLocation');
        $this->addSql('DROP TABLE questionnaireAuthorRight');
        $this->addSql('DROP TABLE questionnaireSkill');
        $this->addSql('DROP TABLE skill_typology');
        $this->addSql('DROP TABLE questionnaireLevel');
        $this->addSql('DROP TABLE clue');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE questionnaire');
        $this->addSql('DROP TABLE questionnaires_revisors');
        $this->addSql('DROP TABLE questionnaires_sourceType');
        $this->addSql('DROP TABLE questionnaires_channel');
        $this->addSql('DROP TABLE questionnaires_socialLocation');
        $this->addSql('DROP TABLE questionnaires_genre');
        $this->addSql('DROP TABLE questionnaires_variety');
        $this->addSql('DROP TABLE rights');
        $this->addSql('DROP TABLE right_user');
        $this->addSql('DROP TABLE right_group');
        $this->addSql('DROP TABLE right_user_someone');
        $this->addSql('DROP TABLE right_user_task');
        $this->addSql('DROP TABLE right_user_session');
        $this->addSql('DROP TABLE right_user_test');
        $this->addSql('DROP TABLE proposition');
        $this->addSql('DROP TABLE levelLansad');
        $this->addSql('DROP TABLE test');
        $this->addSql('DROP TABLE trace');
        $this->addSql('DROP TABLE user_result');
        $this->addSql('DROP TABLE originStudent');
        $this->addSql('DROP TABLE subquestion');
        $this->addSql('DROP TABLE subquestion_focuses');
        $this->addSql('DROP TABLE subquestion_cognitiveOpsMain');
        $this->addSql('DROP TABLE subquestion_cognitiveOpsSecondary');
        $this->addSql('DROP TABLE questionnaireComment');
        $this->addSql('DROP TABLE questionnaireLanguageLevel');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE session_pdo');
        $this->addSql('DROP TABLE clueType');
        $this->addSql('DROP TABLE orderQuestionnaireTest');
        $this->addSql('DROP TABLE typology');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE generalScoreThreshold');
        $this->addSql('DROP TABLE orderQuestionnaireComponent');
        $this->addSql('DROP TABLE componentType');
        $this->addSql('DROP TABLE ignoredLevel');
        $this->addSql('DROP TABLE phasedParams_levels');
        $this->addSql('DROP TABLE skillScoreThreshold');
        $this->addSql('DROP TABLE phasedParams');
        $this->addSql('DROP TABLE component');
        $this->addSql('DROP TABLE general_parameters');
        $this->addSql('DROP TABLE institution');
        $this->addSql('DROP TABLE year');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE answer');
    }
}
