services:
    app.locale_listener:
        class: Innova\SelfBundle\Listener\LocaleSetter
        arguments:
            localeManager: @self.locale.manager
        tags:
            - { name: kernel.event_subscriber }

    self.logout:
        class: Innova\SelfBundle\Listener\LogoutListener
        arguments:  
            security: @security.context
            router: @router

    self.listener.highest_ccu:
        class: Innova\SelfBundle\Listener\HighestCcuListener
        arguments:
            - @key_value_manager
            - @self.user.manager
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
