services:
    self.questionnaire.manager:
        class: Innova\SelfBundle\Manager\Editor\QuestionnaireManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context
            questionnaireRevisorsManager: @self.questionnaire_revisors.manager
            templating:         @templating
            formFactory:        @form.factory
            mediaManager:       @self.media.manager
            questionManager:    @self.question.manager

    self.question.manager:
        class: Innova\SelfBundle\Manager\Editor\QuestionManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            subquestionManager: @self.subquestion.manager

    self.subquestion.manager:
        class: Innova\SelfBundle\Manager\Editor\SubquestionManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            mediaManager:       @self.media.manager
            propositionManager:    @self.proposition.manager

    self.order_questionnaire_test.manager:
        class: Innova\SelfBundle\Manager\Editor\OrderQuestionnaireTestManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.proposition.manager:
        class: Innova\SelfBundle\Manager\Editor\PropositionManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            mediaManager:       @self.media.manager

    self.media.manager:
        class: Innova\SelfBundle\Manager\Media\MediaManager
        arguments:
            entityManager:                  @doctrine.orm.entity_manager
            questionnaireRevisorsManager:   @self.questionnaire_revisors.manager
            #cacheManager:                  @fos_http_cache.cache_manager

    self.app.manager:
        class: Innova\SelfBundle\Manager\Editor\AppManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            propositionManager: @self.proposition.manager

    self.trace.manager:
        class: Innova\SelfBundle\Manager\TraceManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.locale.manager:
        class: Innova\SelfBundle\Manager\LocaleManager
        arguments:
            securityContext:    @security.context
            userManager:        @self.user.manager

    self.user.manager:
        class: Innova\SelfBundle\Manager\UserManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            formFactory:        @form.factory
            fosUserManager:     @fos_user.util.user_manipulator
            session:            @session

    self.comment.manager:
        class: Innova\SelfBundle\Manager\CommentManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context

    self.questionnaire_revisors.manager:
        class: Innova\SelfBundle\Manager\Editor\QuestionnaireRevisorsManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context

    self.answer.manager:
        class: Innova\SelfBundle\Manager\AnswerManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context

    self.mediaclick.manager:
        class: Innova\SelfBundle\Manager\Media\MediaClickManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context

    self.player.manager:
        class: Innova\SelfBundle\Manager\PlayerManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context
            scoreManager:       @self.score.manager

    self.export.manager:
        class: Innova\SelfBundle\Manager\ExportManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            scoreManager:       @self.score.manager
            securityContext:    @security.context
            kernelRoot:         %kernel.root_dir%
            knpSnappyPdf:       @knp_snappy.pdf
            templating:         @templating

    self.test.manager:
        class: Innova\SelfBundle\Manager\Editor\TestManager
        arguments:
            entityManager:                  @doctrine.orm.entity_manager
            securityContext:                @security.context
            questionnaireManager:           @self.questionnaire.manager
            orderQuestionnaireTestManager:  @self.order_questionnaire_test.manager
            phasedTestManager:              @self.phasedtest.manager
            componentManager:               @self.component.manager
            session:                        @session

    self.eec.manager:
        class: Innova\SelfBundle\Manager\Editor\EecManager
        arguments:
            entityManager:          @doctrine.orm.entity_manager
            questionManager:        @self.question.manager
            subquestionManager:     @self.subquestion.manager
            propositionManager:     @self.proposition.manager
            mediaManager:           @self.media.manager

    self.phasedtest.manager:
        class: Innova\SelfBundle\Manager\Editor\PhasedTest\PhasedTestManager
        arguments:
            entityManager:          @doctrine.orm.entity_manager
            questionnaireManager:   @self.questionnaire.manager
            questionManager:        @self.question.manager

    self.score.manager:
        class: Innova\SelfBundle\Manager\ScoreManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context

    self.component.manager:
        class: Innova\SelfBundle\Manager\Editor\PhasedTest\ComponentManager
        arguments:
            entityManager:                      @doctrine.orm.entity_manager
            orderquestionnairecomponentManager: @self.orderquestionnairecomponent.manager

    self.orderquestionnairecomponent.manager:
        class: Innova\SelfBundle\Manager\Editor\PhasedTest\OrderQuestionnaireComponentManager
        arguments:
            entityManager:          @doctrine.orm.entity_manager
            questionnaireManager:   @self.questionnaire.manager

    self.reception.manager:
        class: Innova\SelfBundle\Manager\Identity\ReceptionManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.register.manager:
        class: Innova\SelfBundle\Manager\Identity\RegisterManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.focus.manager:
        class: Innova\SelfBundle\Manager\Identity\FocusManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.cognitiveOp.manager:
        class: Innova\SelfBundle\Manager\Identity\CognitiveOpManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.flow.manager:
        class: Innova\SelfBundle\Manager\Identity\FlowManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.domain.manager:
        class: Innova\SelfBundle\Manager\Identity\DomainManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.authorRight.manager:
        class: Innova\SelfBundle\Manager\Identity\AuthorRightManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.sourceOperation.manager:
        class: Innova\SelfBundle\Manager\Identity\SourceOperationManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.source.manager:
        class: Innova\SelfBundle\Manager\Identity\SourceManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.status.manager:
        class: Innova\SelfBundle\Manager\Identity\StatusManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.typology.manager:
        class: Innova\SelfBundle\Manager\Identity\TypologyManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.skill.manager:
        class: Innova\SelfBundle\Manager\Identity\SkillManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.audioLength.manager:
        class: Innova\SelfBundle\Manager\Identity\AudioLengthManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.textLength.manager:
        class: Innova\SelfBundle\Manager\Identity\TextLengthManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.level.manager:
        class: Innova\SelfBundle\Manager\Identity\LevelManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.language.manager:
        class: Innova\SelfBundle\Manager\Identity\LanguageManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.sourceType.manager:
        class: Innova\SelfBundle\Manager\Identity\SourceTypeManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.channel.manager:
        class: Innova\SelfBundle\Manager\Identity\ChannelManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.genre.manager:
        class: Innova\SelfBundle\Manager\Identity\GenreManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.variety.manager:
        class: Innova\SelfBundle\Manager\Identity\VarietyManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.socialLocation.manager:
        class: Innova\SelfBundle\Manager\Identity\SocialLocationManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.productionType.manager:
        class: Innova\SelfBundle\Manager\Identity\ProductionTypeManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.originStudent.manager:
        class: Innova\SelfBundle\Manager\OriginStudentManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.levelLansad.manager:
        class: Innova\SelfBundle\Manager\LevelLansadManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.clueType.manager:
        class: Innova\SelfBundle\Manager\ClueTypeManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.mediaPurpose.manager:
        class: Innova\SelfBundle\Manager\Media\MediaPurposeManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.mediaType.manager:
        class: Innova\SelfBundle\Manager\Media\MediaTypeManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.componentType.manager:
        class: Innova\SelfBundle\Manager\Editor\PhasedTest\ComponentTypeManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.templating.manager:
        class: Innova\SelfBundle\Manager\TemplatingManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            templating:         @templating

