services:
    self.questionnaire.manager:
        class: Innova\SelfBundle\Manager\QuestionnaireManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            editorLogManager:   @self.editor_log.manager

    self.question.manager:
        class: Innova\SelfBundle\Manager\QuestionManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.subquestion.manager:
        class: Innova\SelfBundle\Manager\SubquestionManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.order_questionnaire_test.manager:
        class: Innova\SelfBundle\Manager\OrderQuestionnaireTestManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.proposition.manager:
        class: Innova\SelfBundle\Manager\PropositionManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.media.manager:
        class: Innova\SelfBundle\Manager\MediaManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.app.manager:
        class: Innova\SelfBundle\Manager\AppManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            propositionManager: @self.proposition.manager

    self.trace.manager:
        class: Innova\SelfBundle\Manager\TraceManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.locale.manager:
        class: Innova\SelfBundle\Manager\LocaleManager
        arguments:
            securityContext:    @security.context
            userManager:        @self.user.manager

    self.user.manager:
        class: Innova\SelfBundle\Manager\UserManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager

    self.comment.manager:
        class: Innova\SelfBundle\Manager\CommentManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context

    self.editor_log.manager:
        class: Innova\SelfBundle\Manager\EditorLogManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context

    self.answer.manager:
        class: Innova\SelfBundle\Manager\AnswerManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context

    self.test.manager:
        class: Innova\SelfBundle\Manager\TestManager
        arguments:
            entityManager:      @doctrine.orm.entity_manager 