services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    twig.extension.array:
        class: Twig_Extensions_Extension_Array
        tags:
            - { name: twig.extension }

    twig.extension.get_languages:
        class: Innova\SelfBundle\Twig\LanguageExtension
        arguments:
            entityManager: @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    twig.extension.get_typologies:
        class: Innova\SelfBundle\Twig\TypologyExtension
        arguments:
            entityManager: @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    twig.extension.disambiguate:
        class: Innova\SelfBundle\Twig\DisambiguateExtension
        tags:
            - { name: twig.extension }

    twig.extension.check_right:
        class: Innova\SelfBundle\Twig\RightExtension
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            securityContext:    @security.context
            rightManager:       @self.right.manager
        tags:
            - { name: twig.extension }

    innova_user.registration.form.type:
        class: Innova\SelfBundle\Form\UserType
        arguments:
            class: %fos_user.model.user.class%
            om: @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: innova_selfbundle_user }

    innova_export:
        class: Innova\SelfBundle\Controller\Features\ExportController
        arguments:
            kernelRoot:         %kernel.root_dir%
            entityManager:      @doctrine.orm.entity_manager
            exportManager:      @self.export.manager
            securityContext:    @security.context

    innova_player:
        class: Innova\SelfBundle\Controller\Player\PlayerController
        arguments:
            securityContext: @security.context
            entityManager: @doctrine.orm.entity_manager
            session: @session
            router: @router
            playerManager: @self.player.manager
            scoreManager: @self.score.manager

    innova_editor_upload:
        class: Innova\SelfBundle\Controller\Features\UploadController
        arguments:
            kernelRoot: %kernel.root_dir%

    innova_editor_questionnaire:
        class: Innova\SelfBundle\Controller\Editor\QuestionnaireController
        arguments:
            questionnaireManager:           @self.questionnaire.manager
            orderQuestionnaireTestManager:  @self.order_questionnaire_test.manager
            entityManager:                  @doctrine.orm.entity_manager
            templating:                     @templating
            questionnaireRevisorsManager:   @self.questionnaire_revisors.manager
            formFactory:                    @form.factory
            securityContext:                @security.context
            rightManager:                   @self.right.manager

    innova_editor_task:
        class: Innova\SelfBundle\Controller\Editor\TaskController
        arguments:
            questionnaireManager:   @self.questionnaire.manager
            questionManager:        @self.question.manager
            orderQuestionnaireTestManager: @self.order_questionnaire_test.manager
            entityManager:      @doctrine.orm.entity_manager
            templating:         @templating
            formFactory:        @form.factory
            securityContext:    @security.context
            rightManager:       @self.right.manager
            session:            @session
            router:             @router

    innova_editor_media:
        class: Innova\SelfBundle\Controller\Editor\MediaController
        arguments:
            mediaManager:       @self.media.manager
            propositionManager: @self.proposition.manager
            appManager:         @self.app.manager
            commentManager:     @self.comment.manager
            entityManager:      @doctrine.orm.entity_manager
            templating:         @templating
            questionnaireRevisorsManager:   @self.questionnaire_revisors.manager
            templatingManager:  @self.templating.manager
            questionnaireManager:           @self.questionnaire.manager
            securityContext:    @security.context
            rightManager:       @self.right.manager
            session:            @session

    innova_editor_subquestion:
        class: Innova\SelfBundle\Controller\Editor\SubquestionController
        arguments:
            mediaManager:       @self.media.manager
            propositionManager: @self.proposition.manager
            subquestionManager: @self.subquestion.manager
            entityManager:      @doctrine.orm.entity_manager
            templating:         @templating
            questionnaireRevisorsManager: @self.questionnaire_revisors.manager
            formFactory:        @form.factory
            rightManager:       @self.right.manager
            securityContext:    @security.context

    innova_editor_eec:
        class: Innova\SelfBundle\Controller\Editor\EecController
        arguments:
            eecManager:                 @self.eec.manager
            propositionManager:     @self.proposition.manager
            entityManager:          @doctrine.orm.entity_manager
            templating:             @templating
            questionnaireRevisorsManager: @self.questionnaire_revisors.manager
            securityContext:    @security.context
            rightManager:       @self.right.manager
            session:            @session

    innova_player_trace:
        class: Innova\SelfBundle\Controller\Player\TraceController
        arguments:
            mediaManager:       @self.media.manager
            propositionManager: @self.proposition.manager
            traceManager:       @self.trace.manager
            answerManager:      @self.answer.manager
            entityManager:      @doctrine.orm.entity_manager
            session:            @session
            router:             @router
            securityContext:    @security.context
            translator:         @translator

    innova_editor_orderquestionnaire:
        class: Innova\SelfBundle\Controller\Editor\OrderQuestionnaireTestController
        arguments:
            entityManager:          @doctrine.orm.entity_manager
            orderQuestionnaireTest: @self.order_questionnaire_test.manager
            questionnaireManager:   @self.questionnaire.manager
            templating:             @templating
            securityContext:    @security.context
            rightManager:       @self.right.manager
            session:            @session

    innova_locale_controller:
        class: Innova\SelfBundle\Controller\Features\LocaleController
        arguments:
            localeManager:          @self.locale.manager

    innova_mediaclick:
        class: Innova\SelfBundle\Controller\Player\MediaClickController
        arguments:
            mediaClickManager: @self.mediaclick.manager

    innova_test:
        class: Innova\SelfBundle\Controller\TestController
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            testManager:    @self.test.manager
            
    innova_editor_proposition:
        class: Innova\SelfBundle\Controller\Editor\PropositionController
        arguments:
            propositionManager:             @self.proposition.manager
            templating:                     @templating
            questionnaireRevisorsManager:   @self.questionnaire_revisors.manager
            securityContext:    @security.context
            rightManager:       @self.right.manager

    pdo:
        class: PDO
        arguments:
            dsn:      "mysql:dbname=%database_name%"
            user:     %database_user%
            password: %database_password%
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, %pdo.db_options%]
        