services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    twig.extension.array:
        class: Twig_Extensions_Extension_Array
        tags:
            - { name: twig.extension }

    innova_user.registration.form.type:
        class: Innova\SelfBundle\Form\UserType
        arguments:
            class: %fos_user.model.user.class%
            om: @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: innova_selfbundle_user }

    innova_import:
        class: Innova\SelfBundle\Controller\ImportController
        arguments:
            kernelRoot: %kernel.root_dir%
            entityManager: @doctrine.orm.entity_manager

    innova_export:
        class: Innova\SelfBundle\Controller\ExportController
        arguments:
            kernelRoot: %kernel.root_dir%
            entityManager: @doctrine.orm.entity_manager

    innova_export_tia:
        class: Innova\SelfBundle\Controller\ExportTiaController
        arguments:
            kernelRoot: %kernel.root_dir%
            entityManager: @doctrine.orm.entity_manager

    innova_player:
        class: Innova\SelfBundle\Controller\Player\PlayerController
        arguments:
            securityContext: @security.context
            entityManager: @doctrine.orm.entity_manager
            session: @session
            router: @router

    innova_editor_upload:
        class: Innova\SelfBundle\Controller\Editor\UploadController
        arguments:
            kernelRoot: %kernel.root_dir%
        calls:
            - [setRequest, [@request]]
        scope: request

    innova_editor_questionnaire:
        class: Innova\SelfBundle\Controller\Editor\QuestionnaireController
        arguments:
            questionnaireManager:   @self.questionnaire.manager
            questionManager:    @self.question.manager
            orderQuestionnaireTestManager: @self.order_questionnaire_test.manager
            entityManager:      @doctrine.orm.entity_manager
            templating:         @templating
        calls:
            - [setRequest, [@request]]
        scope: request

    innova_editor_media:
        class: Innova\SelfBundle\Controller\Editor\MediaController
        arguments:
            mediaManager:       @self.media.manager
            propositionManager: @self.proposition.manager
            appManager:         @self.app.manager
            entityManager:      @doctrine.orm.entity_manager
            templating:         @templating
        calls:
            - [setRequest, [@request]]
        scope: request

