parameters:
    faye_server.adapter.class:  Nc\FayeClient\Adapter\CurlAdapter
    faye_server.client.class:   Nc\FayeClient\Client
services:
    innova_voter:
        class: Innova\SelfBundle\Voter\Voter
        arguments:
            securityContext:    @security.token_storage
            rightManager:       @self.right.manager

    innova_user.registration.form.type:
        class: Innova\SelfBundle\Form\UserType
        arguments:
            class: %fos_user.model.user.class%
            om: @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: innova_selfbundle_user }

    innova_export:
        class: Innova\SelfBundle\Controller\ExportController
        arguments:
            kernelRoot:         %kernel.root_dir%
            exportManager:      @self.export.manager
            securityContext:    @security.token_storage
            rightManager:       @self.right.manager
            voter:              @innova_voter
            session:            @session

    innova_editor_upload:
        class: Innova\SelfBundle\Controller\UploadController
        arguments:
            kernelRoot: %kernel.root_dir%

    innova_editor_questionnaire:
        class: Innova\SelfBundle\Controller\Editor\QuestionnaireController
        arguments:
            questionnaireManager:           @self.questionnaire.manager
            templating:                     @templating
            voter:                          @innova_voter

    innova_editor_task:
        class: Innova\SelfBundle\Controller\TaskController
        arguments:
            taskManager:            @self.task.manager
            questionnaireManager:   @self.questionnaire.manager
            questionManager:        @self.question.manager
            orderQuestionnaireTestManager: @self.order_questionnaire_test.manager
            entityManager:      @doctrine.orm.entity_manager
            formFactory:        @form.factory
            securityContext:    @security.token_storage
            voter:              @innova_voter
            rightManager:       @self.right.manager

    innova_editor_media:
        class: Innova\SelfBundle\Controller\MediaController
        arguments:
            mediaManager:               @self.media.manager
            propositionManager:         @self.proposition.manager
            appManager:                 @self.app.manager
            commentManager:             @self.comment.manager
            entityManager:              @doctrine.orm.entity_manager
            templating:                 @templating
            revisorManager:             @self.questionnaire_revisors.manager
            templatingManager:          @self.templating.manager
            questionnaireManager:       @self.questionnaire.manager
            securityContext:            @security.token_storage
            rightManager:               @self.right.manager

    innova_editor_subquestion:
        class: Innova\SelfBundle\Controller\Editor\SubquestionController
        arguments:
            subquestionManager: @self.subquestion.manager
            templating:         @templating
            voter:              @innova_voter

    innova_editor_eec:
        class: Innova\SelfBundle\Controller\Editor\EecController
        arguments:
            eecManager:                     @self.eec.manager
            templating:                     @templating
            questionnaireRevisorsManager:   @self.questionnaire_revisors.manager
            voter:                          @innova_voter

    innova_editor_answer:
        class: Innova\SelfBundle\Controller\Editor\AnswerController
        arguments:
            eecManager:             @self.eec.manager
            propositionManager:     @self.proposition.manager
            templating:             @templating
            voter:                  @innova_voter

    innova_player_trace:
        class: Innova\SelfBundle\Controller\TraceController
        arguments:
            traceManager:       @self.trace.manager
            session:            @session
            router:             @router
            kernel:             @http_kernel

    innova_editor_orderquestionnaire:
        class: Innova\SelfBundle\Controller\Editor\OrderQuestionnaireTestController
        arguments:
            orderQuestionnaireTest: @self.order_questionnaire_test.manager
            questionnaireManager:   @self.questionnaire.manager
            templating:             @templating
            voter:                  @innova_voter

    innova_mediaclick:
        class: Innova\SelfBundle\Controller\MediaClickController
        arguments:
            mediaClickManager: @self.mediaclick.manager

    innova_test:
        class: Innova\SelfBundle\Controller\TestController
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            testManager:        @self.test.manager

    innova_editor_proposition:
        class: Innova\SelfBundle\Controller\Editor\PropositionController
        arguments:
            propositionManager:             @self.proposition.manager
            templating:                     @templating
            voter:                          @innova_voter

    innova_general_parameters:
        class: Innova\SelfBundle\Controller\GeneralParametersController
        arguments:
            entityManager:          @doctrine.orm.entity_manager
            voter:                  @innova_voter
            generalParamsManager:   @self.generalparams.manager
            router:                 @router

    innova_institution:
        class: Innova\SelfBundle\Controller\Institution\InstitutionController
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            voter:              @innova_voter
            router:             @router
            formFactory:        @form.factory
            session:            @session

    innova_course:
        class: Innova\SelfBundle\Controller\Institution\CourseController
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            voter:              @innova_voter
            router:             @router
            formFactory:        @form.factory
            session:            @session

    innova_year:
        class: Innova\SelfBundle\Controller\Institution\YearController
        arguments:
            entityManager:      @doctrine.orm.entity_manager
            voter:              @innova_voter
            router:             @router
            formFactory:        @form.factory
            session:            @session

    pdo:
        class: PDO
        arguments:
            dsn:      "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            user:     %database_user%
            password: %database_password%
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    innova_locale_controller:
        class: Innova\SelfBundle\Controller\LocaleController
        arguments:
            localeManager:          @self.locale.manager

    key_value_manager:
        class: Innova\SelfBundle\Manager\KeyValueManager
        arguments:
            - @doctrine.orm.entity_manager
